//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuInicio.LN {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LN_1_3_GenerarCertificadoTrabajo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LN_1_3_GenerarCertificadoTrabajo() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MenuInicio.LN.LN-1_3_GenerarCertificadoTrabajo", typeof(LN_1_3_GenerarCertificadoTrabajo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=17,Y=95}.
        /// </summary>
        internal static System.Drawing.Point chronosDataSet_Sueldos_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("chronosDataSet_Sueldos.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=17,Y=17}.
        /// </summary>
        internal static System.Drawing.Point chronosDataSet78_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("chronosDataSet78.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=563,Y=17}.
        /// </summary>
        internal static System.Drawing.Point chronosDataSet79_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("chronosDataSet79.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=233,Y=56}.
        /// </summary>
        internal static System.Drawing.Point chronosDataSet80_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("chronosDataSet80.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=724,Y=56}.
        /// </summary>
        internal static System.Drawing.Point chronosDataSet82_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("chronosDataSet82.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=384,Y=56}.
        /// </summary>
        internal static System.Drawing.Point puestosBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("puestosBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=875,Y=56}.
        /// </summary>
        internal static System.Drawing.Point puestosBindingSource1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("puestosBindingSource1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=557,Y=56}.
        /// </summary>
        internal static System.Drawing.Point puestosTableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("puestosTableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=1055,Y=56}.
        /// </summary>
        internal static System.Drawing.Point puestosTableAdapter1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("puestosTableAdapter1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=203,Y=95}.
        /// </summary>
        internal static System.Drawing.Point sueldosBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("sueldosBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=375,Y=95}.
        /// </summary>
        internal static System.Drawing.Point sueldosTableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("sueldosTableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=714,Y=17}.
        /// </summary>
        internal static System.Drawing.Point tipoDocumentosBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("tipoDocumentosBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=17,Y=56}.
        /// </summary>
        internal static System.Drawing.Point tipoDocumentosTableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("tipoDocumentosTableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=168,Y=17}.
        /// </summary>
        internal static System.Drawing.Point tipoLicenciasBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("tipoLicenciasBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Point similar a {X=368,Y=17}.
        /// </summary>
        internal static System.Drawing.Point tipoLicenciasTableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("tipoLicenciasTableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
    }
}
